import "@/app/layout.js";
import Image from "next/image";

export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};
  

export default function About() {
    return (
      <main>

      <section id="aboutIntro">
        <br />
        <br />
        <br />
        <h2>Cantor College was established in 1989 to specialize in Computing and Design.</h2>
        {/* <Image src="/Images/AboutTitle.png" alt="About Us" width={100} height={100} /> */}
      </section>
      <h2>About Our College</h2>
      <div id="dividerHeading" />
      <p>
        At Cantor College, we want to give students the education they need to achieve their career aims, 
        leaving them equipped with the knowledge, skills and experience to succeed.  
      </p>
      <p>
        Cantor College gives you the opportunities that can give you the edge when you enter the world of work, 
        through our teaching and our links to some of the world's leading researchers and employers.
      </p>
      <p>Our students have gone on to successful careers in a wide range of industries across the globe.</p>
      <p>
      Whatever your ambitions, our learning and support can help to get the most out of your time with Cantor College, 
      both as a student and in your future career.
      </p>
      <div id="dividerHeading" />
      <br />
      <section className="aboutImages">
      <div className="row1">
        <div className="col">
          <Image src="/Images/Lecture3.jpg" alt="About Us" width={300} height={300} /> 
        </div>
        <div className="spaceCol" />
        <div className="col">
          <Image src="/Images/PlaystationLab.jpg" alt="About Us" width={300} height={300} /> 
        </div>
        <div className="spaceCol" />
        <div className="col">
        <Image src="/Images/Collaborative.jpeg" alt="About Us" width={300} height={300} /> 
        </div>
      </div>

      <div className="row2">
        <div className="colT">
          <p>Lecture Theatres</p>
        </div>
        <div className="spaceCol" />
        <div className="colT">
          <p>Computing Labs</p>
        </div>
        <div className="spaceCol" />
        <div className="colT">
        <p>Collaborative Work</p>
        </div>
      </div>
      </section>

      <br />
      <div id="dividerSection" />

      <section id="Location">
        <h2>How To Find Us</h2>
        <div id="dividerHeading" />
        <div className="address">
          <Image src="/Images/CityMap.jpg" alt="About Us" width={500} height={299} /> 
          <div className="addressDetails">
            <h2>Our Address</h2>
            <p>Cantor College</p>
            <p>Main Street</p>
            <p>Sheffield</p>
            <p>SC4 2BB</p>
          </div>
        </div>
      </section>
      </main>
    );
  }