export const metadata = {
  title: "About Us",
  description: "Generated by create next app",
};
  

export default function About() {
    return (
      <div>
        <h2>Staff</h2>
      </div>
    );
  }