import "@/app/layout.js";
import Image from "next/image";
import Link from "next/link";
export const metadata = {
    title: "Our Courses",
    description: "Generated by create next app",
  };
  

export default function Courses() {
    return (
      <main>
        <section id="coursesIntro">
          <h2>Computing & Design Courses</h2>
        </section>
        <h2>Computing Courses</h2>
        <div id="dividerHeading" />
        <section id="computingText">
          <Image src="/Images/computing.jpg" alt="Computing" width={374} height={200} />
          <p>
            The College offers a range of courses to suit applicants with varying backgrounds and educational abilities. 
            At undergraduate level, there are single BSc Honours Degree courses in Computing, Computer Networks, 
            Software Engineering and Cyber Security with Forensics amongst others.
          </p>
          <div id="smallDivider" />
          <p>
            The College teaches undergraduate and postgraduate courses in a wide range of specialisms, 
            including computer science, software development, information systems, networking and software engineering. 
            It is at the heart of a passionate computing community, including student societies devoted to games development, 
            digital forensics and programming.
          </p>
          <div id="smallDivider" />
          <p>
            The courses are British Computer Society accredited and are highly relevant to modern industry. 
            They are designed to prepare students for professional occupations in Computing and related fields. 
            Many graduates continue their studies to pursue a higher degree such as an MSc. or PhD.
          </p>
          <Link id="computingLink" href="/courses/computing">Click here to view our list of Computing Courses</Link> 
        </section>
          <div id="dividerSection" />

        <h2>Design Courses</h2>
        <div id="dividerHeading" />
        <section id="designText">
          <Image src="/Images/design.jpg" alt="Design" width={374} height={200} />
          <p>
            The College is an internationally connected creative community of diverse disciplines housed under one roof. 
            We shape our students' futures, preparing them to shape the world through applied knowledge and creativity.
          </p>
          <div id="smallDivider" />
          <p>
            The College's art and design courses don't just train you, they promote alternative ways of thinking, making and communicating; 
            they provide you with space, tools and inspiration to develop your creative practice and a clear career path. 
            You'll get expert teaching from active practitioners and researchers who will encourage you to adopt innovative and resourceful 
            approaches that both perceive and create opportunities for better lives.
          </p>
          <div id="smallDivider" />
          <p>
            The courses are British Computer Society accredited and are highly relevant to modern industry. 
            They are designed to prepare students for professional occupations in Computing and related fields. 
            Many graduates continue their studies to pursue a higher degree such as an MSc. or PhD.
          </p>
          <Link id="designLink" href="/courses/design">Click here to view our list of Design Courses</Link> 
        </section>
      </main>
    );
  }