export const metadata = {
    title: "Our Facilities",
    description: "Generated by create next app",
  };
  

export default function Facilities() {
    return (
      <div>
        <h2>Staff</h2>
      </div>
    );
  }