import { FacilitiesSlides } from "../components/slideshow";

export const metadata = {
    title: "Our Facilities",
    description: "Generated by create next app",
  };
  

export default function Facilities() {
    return (
      <div>
        <h2>College Facilities</h2>
        <p>The College is located in the attractive and pleasantly refurbished Building.</p>
        <p>The building houses computing laboratories, and lecture/tutorial rooms. It has its own catering facilities and student work areas. 
        There is also a car park to the back of the building.</p>
        <p>Our building has space of 9500m², houses over 240 staff and provides teaching space for more than 1600 students.</p>

        <h3>Facilities include:</h3>
        <ul>
            <li>wi-fi technology</li>
            <li>pool teaching rooms, including classrooms to teach from 25 - 80 students</li>
            <li>specialist faculty facilities</li>
            <li>a double height lecture theatre at first and second floor level</li>
            <li>dramatic three-storey glass open atrium</li>
            <li>meeting rooms</li>
            <li>office accommodation</li>
            <li>specialist IT facilities</li>
            <li>reception desk area</li>
            <li>catering outlet</li>
            <li>parking for disabled badge holders</li>
            <li>cycle racks</li>
        </ul>
        <FacilitiesSlides />
      </div>
    );
  }