export const metadata = {
    title: "Contact Us",
    description: "Generated by create next app",
  };
  

export default function Contact() {
    return (
      <div>
        <h2>Staff</h2>
      </div>
    );
  }