export const metadata = {
    title: "Work with Us",
    description: "Generated by create next app",
  };
  

export default function Business() {
    return (
      <div>
        <h2>Staff</h2>
      </div>
    );
  }