import "./layout.js";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};


const Home = () => {
  return (
    <main>
      <section id="slideshow">
        <p>My Slideshow</p>
      </section>
    </main>
  );
};

export default Home;