import { fetchComputing } from "@/app/lib/dbComp";
import Link from "next/link";
export const metadata = {
    title: "Computing Courses",
    description: "Generated by create next app",
  };
  
const Computing = async () => {
  const computing = await fetchComputing();

    return (
      <div>
        <h2>Computing Courses</h2>
        <ul className="ComputingList">
          {computing.map((computing, index) => (
            <li key={index}>
              <br />
              <Link href={`./computing/${computing.id}`}>{computing.CourseTitle}</Link>
              <br />
            </li>
          ))}
        </ul>
      </div>
    );
  };
  export default Computing;