import { fetchComputing } from "@/app/lib/db";
export const metadata = {
    title: "Computing Courses",
    description: "Generated by create next app",
  };
  
const Computing = async () => {
  const computing = await fetchComputing();

    return (
      <div>
        <h2>Computing Courses</h2>
        <ul>
          {computing.map((computing, index) => (
            <li key={index}>
              {computing.CourseTitle} {computing.CourseType}
            </li>
          ))}
        </ul>
      </div>
    );
  };
  export default Computing;