export const metadata = {
    title: "Computing Courses",
    description: "Generated by create next app",
  };
  

export default function Computing() {
    return (
      <div>
        <h2>Staff</h2>
      </div>
    );
  }