export const metadata = {
    title: "Staff Information",
    description: "Generated by create next app",
  };
  

export default function Staff() {
    return (
      <div>
        <h2>Information for Staff</h2>
        <h3>News</h3>
        Cantor College recently hosted the Software Engineering student of the year awards. Short-listed candidates from around the country attended the one day event.
        <h3>Academic Registry</h3>
        For academic regulations, assessment, awards, student records and course validation.
        <h3>Catering Services</h3>
        Contact the Catering Services regarding on and off-site catering.
        <h3>Financial Services</h3>
        The financial team based on the 2nd Floor are responsible for all areas of student finance as 
        well as College budgeting.
        <h3>Information Systems Services</h3>
        The ISS team delivers the College's computing facilities including all hardware and software. 
        They also run the staff helpdesk.
        <h3>Marketing Services</h3>
        The Marketing Team will help promote events and new courses. They will help with press 
        release preparation.
        <h3>Personnel Services</h3>
        All staff pay and conditions enquiries should be directed to the Personnel Services team on 
        the 3rd floor.
        <h3>Facilities</h3>
        The facilities are responsible for the general care and maintenance of the College. All 
        enquiries via the main helpdesk.
      </div>
    );
  }